<a href="https://colab.research.google.com/github/dlwodud04/ai-mathematics/blob/main/23-04-18/%EC%A0%84%EC%B9%98%ED%96%89%EB%A0%AC%2C%EC%97%AD%ED%96%89%EB%A0%AC%2C%EC%9C%A0%EC%82%AC%EC%97%AD%ED%96%89%EB%A0%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**전치 행렬** 

*행렬의 내적에 대한 정의*
- 일반적으로 수학에서는 행렬의 내적을 다루지 않습니다,
- 하지만 numpy의np.inner를 사용하면 i번쨰 행벡터와 j번째 행벡터 사이의 내적을 성분으로 가지는 행렬을 계산합니다.

In [2]:
import numpy as np

A = np.array([[1,2,3],
              [2,4,3]])
B = np.array([[3,2,1],
              [1,2,1],
              [1,1,3]])

np.inner(A,B)

array([[10,  8, 12],
       [17, 13, 15]])

**연산자로서의 행렬**
- 행렬은 벡터공간에서 사용할 수 있는 연산자로 이해할 수 있습니다
- 행렬곱을 활용하여 벡터를 다른 차원의 공간으로 이동시킬 수 있습니다

**역행렬의 성질**
- 역행렬은 행과 열의 숫자가 동일하고 행렬식이 0이 아닌 경우에만 계산할 수 있습니다. 

-  [a b] = [d -b]
-  [c d] = [-c a]
- ad-bc

In [3]:
import numpy as np

A = np.array([[1,2],
              [3,4]])

np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [4]:
A @ np.linalg.inv(A)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

**유사역행렬**
- 만약 역행렬을 계산할 수 없다면, 유사역행렬(pseudo-inverse) 또는 무어-펜로즈(Moore-Penrose) 역행렬 A+을 이용합니다.

In [6]:
import numpy as np

Y = np.array([[0,1],
              [1,-1],
              [2,1]])

np.linalg.pinv(Y)

array([[-0.07142857,  0.28571429,  0.35714286],
       [ 0.35714286, -0.42857143,  0.21428571]])

In [7]:
np.linalg.pinv(Y) @ Y

array([[ 1.00000000e+00,  0.00000000e+00],
       [-1.66533454e-16,  1.00000000e+00]])