<a href="https://colab.research.google.com/github/dlwodud04/ai-mathematics/blob/main/23-03-28/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5_%EC%88%98%ED%95%99(%EB%B2%A1%ED%84%B0).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**벡터의 스칼라곱에 대한 코딩 실습**
- 벡터의 스칼라곱에 대한 코딩 실습
- a=2, X=[1,2,3]일때, aX를 구하시오

In [5]:
import numpy as np

a = 2
x = np.array([1,2,3])

m=(a*x)

print(m)

[2 4 6]


**벡터의 합에 대한 코딩 실습**
- 벡터의 합에 대한 코딩 실습
- X=[1,2,3],Y=[4,5,6]일때, X+Y를 구하시오

In [6]:
x = np.array([1,2,3])
y = np.array([4,5,6])

s = x+y

print(s)

[5 7 9]


In [8]:
x = [1,2,3,4,5]
y = [3,4,5]

c = x+y

print(c)

[1, 2, 3, 4, 5, 3, 4, 5]


**벡터의 차에 대한 코딩 실습**
- 벡터의 차에 대한 코딩 실습
- X=[1,2,3],Y=[4,5,6]일때, X-Y를 구하시오

In [9]:
x = np.array([1,2,3])
y = np.array([4,5,6])

s = x-y

print(s)

[-3 -3 -3]


**벡터의 성분곱에 대한 코딩 실습**
- 벡터의 성분곱에 대한 코딩 실습
- X=[1,2,3],Y=[4,5,6]일때, X o Y를 구하시오

In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])

h = a*b

print(h)

[ 4 10 18]


In [12]:
x = [1,2,3]
y = [4,5,6]

s = x+y

print(s)

[1, 2, 3, 4, 5, 6]


**L1 노름에 대한 코딩 실습**
- L1 노름에 대한 코딩 실습
- X=[3,4]일때, L1노름을 구하시오

In [13]:
import numpy as np

def L1_norm(x) : 
    a = np.abs(x)
    s = np.sum(a)
    return s

x = np.array([3,4])

print(L1_norm(x))

7


**L2 노름에 대한 코딩 실습**
- L2 노름에 대한 코딩 실습
- X=[3,4]일때, L2노름을 구하시오

In [14]:
import numpy as np

def L2_norm(x) : 
    # return np.sqrt(np.sum(x **2))
    p = x*x
    s = np.sum(p)
    r = np.sqrt(s)
    return r

x = np.array([3,4])

print(L2_norm(x))

5.0


**두 벡터 사이의 각도에 대한 코딩 실습**
- 두 벡터 사이의 각도에 대한 코딩 실습
- x = [4, 0] , y = [4, 3]일 때, 두 벡터 사이의 각도를 구하시오

In [16]:
import numpy as np

def L2_Norm(x):
    return np.sqrt(np.sum(x**2))

def angle(x,y):
    cos_theta = np.inner(x,y) / (L2_Norm(x) * L2_Norm(y))
    theta = np.arccos(cos_theta)
    return theta

a = np.array([4,0])
b = np.array([4,3])
angle(a,b)

0.6435011087932843