<a href="https://colab.research.google.com/github/dlwodud04/ai-mathematics/blob/main/23-05-16/Derivative_Training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**함수 f(x)의 미분에 대한 해석**
- 입력변수x가 (아주 미세하게) 변할때, 함수f(x)의 변화량을 나타내는 식
- 함수f(x)가 입력 값 x의미세한 변화에 얼마나 민감하게 반응하는지 나타내는 식

**편미분에 대한 정의**

- 편미분은 입력 변수가 2개 이상인 다변수 함수에서 미분하고자 하는 변수 1개를 제외한 나머지 변수들은 상수로 취급하고, 특정한 한 변수에 대해서만 미분하는
것을 의미합니다.

**체인룰**
- 체인룰이란 합성함수를 미분하기 우해 사용한 방식입니다
- 합성함수란 여러 함수로 구성된 함수
- 합성함수를 미분하기 위해서 '합성함수를 구성하는 각 함수의 미분의 곱'으로 나타내는 체인룰을 이용합니다.


**수치미분**
- 수수치미분(Numerical Derivative)이란 C언어나 파이썬 등의 프로그래밍 언어를 이용하여 미분 값, 
즉 입력 값이 아주 미세하게 변할 때 함수𝑓는 얼마나 변하는지 계산하는 것을 의미
합니다


**다변수 함수의 수치미분**
- 입력 변수가 2개 이상인 다변수 함수의 경우 각각의 입력 변수는 서로 독립적이기 때문에 수치미분 또한 각각의 변수만큼 개별적으로 계산해야 합니다.


**np.zero와 np.zeros_like**
- np.zero는 0으로 이루어진 array를 출력합니다. 해당 array에는 tuple 또는 int 또는 list의 값이 포함되어 있어야 합니다. 그러면 해당하는 shape의 array로 반환합니다.
- np.zero_like는 어떤 변수만큼의 사이즈인 0으로 이루어진 array를 출력합니다. 여기에는 변수가 들어와야 합니다. 변수 외에 [2, 3, 3]가 같이 parameter로 넣어주어도 되며, 단, 2, 3, 3 shape를 가진 array를 가지고 나오는 것이 아니 [0, 0 ,0]이 numpy array가 출력됩니다


**numpy iterator**
- 인덱싱이나 슬라이싱과 같이 행렬의 원소를 하나씩 가져오는 방법 외에 행렬의 모든 원소를 처음부터 끝까지 하나씩 가져오기 위해서는 이터레이터의 방법을 가장 많이 사용합니다.
- numpy에서의 이터레이터는 C++, Java에서의 이터레이터 처럼 next 메서드를 통해서 데이터의 처음부터 끝까지 순차적으로 읽어들이는 방법을 제공하고 있습니다.

In [1]:
# 함수 𝑓 𝑥 = 𝑥²미분계수 𝑓^t(3.0) 계산 실습

import numpy as np
# 미분 공식 구현
def numerical_derivative(f,x):
    delta = 1e-5
    diff_x = (f(x+delta) - f(x-delta)) / (2*delta)
    return diff_x

# 미분 대상 함수
def func1(x):
    return x**2

result = numerical_derivative(func1, 3.0)
print(result)

6.000000000039306


In [2]:
# 함수 𝑓 𝑥 = 3𝑥e^x 미분계수 𝑓'(2.0) 계산 실습

import numpy as np
# 미분 공식 구현
def numerical_derivative(f,x):
    delta = 1e-5
    diff_x = (f(x+delta) - f(x-delta)) / (2*delta)
    return diff_x

# 미분 대상 함수
def func2(x):
    return 3*x*(np.exp(x))

result = numerical_derivative(func2, 2.0)
print(result)

66.50150489306839


In [3]:
# 수학공식 검증

print(3*np.exp(2)+ 3*2*np.exp(2))

66.50150489037586


In [4]:
# np.zeros

import numpy as np

a = np.zeros([2,3,3])

a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [5]:
b = np.zeros((2,3,3))

b

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [6]:
# np.zeros_like
a = np.zeros_like((2,3,3,10))
b = np.zeros_like(a)

b

array([0, 0, 0, 0])

In [7]:
a = np.zeros_like([2,3,3,10])
b = np.zeros_like(a)

b

array([0, 0, 0, 0])

In [8]:
# numpy iterator

import numpy as np

A = np.array([[10,20,30,40],[50,60,70,80]])

print(A)
print(A.shape)

it = np.nditer(A,flags=['multi_index'],op_flags=['readwrite'])

while not it.finished:
    idx = it.multi_index
    print('index =>', idx, 'value=>', A[idx])
    it.iternext()

[[10 20 30 40]
 [50 60 70 80]]
(2, 4)
index => (0, 0) value=> 10
index => (0, 1) value=> 20
index => (0, 2) value=> 30
index => (0, 3) value=> 40
index => (1, 0) value=> 50
index => (1, 1) value=> 60
index => (1, 2) value=> 70
index => (1, 3) value=> 80


In [17]:
# numpy iterator에 대한 코딩 실습

import numpy as np

def numerical_derivative(f,x): # f는 미분하고자 하는 다변수 함수 , x는 모든 변수를 포함하고 있는 numpy 객체(배열,행렬,....)
    delta_x = 1e-5
    grad = np.zeros_like(x) # 1. 계산된 수치미분 값 저장 변수
    it = np.nditer(x,flags=['multi_index'],op_flags=['readwrite']) # 2. 모든 입력변수에 대해 편미분하기 위해 iterator 획득 
    while not it.finished:
        idx = it.multi_index
        tmp_x = x[idx] # 3. numpy 타입은 mutable 이므로 원래 값 보관
        x[idx] = float(tmp_x) + delta_x # 4,하나의 변수에 대한 수치미분 계산
        fx1 = f(x) #f(x+delta_x)

        x[idx] = tmp_x - delta_x
        fx2 = f(x) #f(x-delta_x)
        grad[idx] = (fx1-fx2) / (2*delta_x)

        x[idx] - tmp_x
        it.iternext()
    
    return grad


In [18]:
# 1변수 함수, f(x) = x^2, f(3.0)

import numpy as np

def numerical_derivative(f,x): # f는 미분하고자 하는 다변수 함수 , x는 모든 변수를 포함하고 있는 numpy 객체(배열,행렬,....)
    delta_x = 1e-5
    grad = np.zeros_like(x) # 1. 계산된 수치미분 값 저장 변수
    print("debug 1, initial input variable = ", x)
    print("debug 2, initual grad = ", grad)
    print("======================================")

    it = np.nditer(x,flags=['multi_index'],op_flags=['readwrite']) # 2. 모든 입력변수에 대해 편미분하기 위해 iterator 획득 
    while not it.finished:
        idx = it.multi_index

        print("debug 3, idx = ", idx ,",x[idx] = ", x[idx])

        tmp_x = x[idx] # 3. numpy 타입은 mutable 이므로 원래 값 보관
        x[idx] = float(tmp_x) + delta_x # 4,하나의 변수에 대한 수치미분 계산
        fx1 = f(x) #f(x+delta_x)

        x[idx] = tmp_x - delta_x
        fx2 = f(x) #f(x-delta_x)
        grad[idx] = (fx1-fx2) / (2*delta_x)

        print("debug 4, grad[idx] = ", grad[idx])
        print("debug 5, grad = ", grad)
        print("================================")

        x[idx] - tmp_x
        it.iternext()

    return grad

def func4(input_obj):
    x = input_obj[0]
    y = input_obj[1]
    return 2*x + 3*x*y + np.power(y,3)
    
# (x, y) = (1.0, 2.0)
input = np.array([1.0,2.0])
numerical_derivative(func4,input)

debug 1, initial input variable =  [1. 2.]
debug 2, initual grad =  [0. 0.]
debug 3, idx =  (0,) ,x[idx] =  1.0
debug 4, grad[idx] =  8.00000000005241
debug 5, grad =  [8. 0.]
debug 3, idx =  (1,) ,x[idx] =  2.0
debug 4, grad[idx] =  14.99997000022901
debug 5, grad =  [ 8.      14.99997]


array([ 8.     , 14.99997])

In [19]:
# 4변수 함수, f(w,x,y,z) = wx + yz + 3w + zy^2, f'(1.0, 2.0, 3.0, 4.0)

import numpy as np

def numerical_derivative(f,x): # f는 미분하고자 하는 다변수 함수 , x는 모든 변수를 포함하고 있는 numpy 객체(배열,행렬,....)
    delta_x = 1e-5
    grad = np.zeros_like(x) # 1. 계산된 수치미분 값 저장 변수
    print("debug 1, initial input variable = ", x)
    print("debug 2, initual grad = ", grad)
    print("======================================")

    it = np.nditer(x,flags=['multi_index'],op_flags=['readwrite']) # 2. 모든 입력변수에 대해 편미분하기 위해 iterator 획득 
    while not it.finished:
        idx = it.multi_index

        print("debug 3, idx = ", idx ,",x[idx] = ", x[idx])

        tmp_x = x[idx] # 3. numpy 타입은 mutable 이므로 원래 값 보관
        x[idx] = float(tmp_x) + delta_x # 4,하나의 변수에 대한 수치미분 계산
        fx1 = f(x) #f(x+delta_x)

        x[idx] = tmp_x - delta_x
        fx2 = f(x) #f(x-delta_x)
        grad[idx] = (fx1-fx2) / (2*delta_x)

        print("debug 4, grad[idx] = ", grad[idx])
        print("debug 5, grad = ", grad)
        print("================================")

        x[idx] - tmp_x
        it.iternext()

    return grad

def func5(input_obj):
    w = input_obj[0,0]
    x = input_obj[0,1]
    y = input_obj[1,0]
    z = input_obj[1,1]
    return (w*z + w*y*z + 3*w + z*np.power(y,2))

# 입력을 2x2행렬로 구성
input = np.array([[1.0, 2.0],[3.0,4.0]])
numerical_derivative(func5, input)

debug 1, initial input variable =  [[1. 2.]
 [3. 4.]]
debug 2, initual grad =  [[0. 0.]
 [0. 0.]]
debug 3, idx =  (0, 0) ,x[idx] =  1.0
debug 4, grad[idx] =  19.000000000346517
debug 5, grad =  [[19.  0.]
 [ 0.  0.]]
debug 3, idx =  (0, 1) ,x[idx] =  2.0
debug 4, grad[idx] =  0.0
debug 5, grad =  [[19.  0.]
 [ 0.  0.]]
debug 3, idx =  (1, 0) ,x[idx] =  3.0
debug 4, grad[idx] =  27.999960000357756
debug 5, grad =  [[19.       0.     ]
 [27.99996  0.     ]]
debug 3, idx =  (1, 1) ,x[idx] =  4.0
debug 4, grad[idx] =  12.999890000031654
debug 5, grad =  [[19.       0.     ]
 [27.99996 12.99989]]


array([[19.     ,  0.     ],
       [27.99996, 12.99989]])